defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

url: "https://help.geneea.com"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
